networks:
  monitor-net:
    driver: bridge

services:
  poifier-client:
    container_name: poifier-client
    image: grassets/poifier-client
    networks:
       - monitor-net
    restart: unless-stopped
    tty: true
    command: 
      - '--graph-node-status-endpoint=${GRAPH_NODE}'
      - '--poifier-server=${POI_SERVER}'
      - '--mnemonic=${MNEMONIC}'
      - '--indexer-address=${INDEXER_ADDRESS}'
      - '--indexer-agent-epoch-subgraph-endpoint=${INDEXER_AGENT_EPOCH_SUBGRAPH_ENDPOINT}'
